apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-svc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-svc
  template:
    metadata:
      labels:
        app: demo-svc
    spec:
      containers:
        - name: demo-svc
          image: "{{ .Values.image }}"
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20