apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app: demo-svc
