apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argodemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argodemo
  template:
    metadata:
      labels:
        app: argodemo
    spec:
      containers:
      - name: node-app
        image: paradoxinversion/containerized-node-app
        ports:
        - containerPort: 8080
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause:
          duration: 1m
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 75
      - pause: {}
