apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keptn.service }}
  namespace: {{ .Release.Namespace }} 
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: demo-svc
  
