apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: {{ .Release.Namespace }} 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo-svc
  
