apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9090
      NodePort: 30000
  selector:
    app: prometheus-server
  