apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-demo"
spec:
  stages:
    - name: "hardening"
      sequences:
      - name: "delivery"
        tasks:
          - name: "deployment"
            properties:
              deploymentstrategy: "direct"
          - name: "release"
      - name: "delivery-direct"
        tasks:
          - name: "deployment"
            properties:
              deploymentstrategy: "direct"
          - name: "release"