---
spec_version: '1.0'
indicators:
  request_duration_p50: histogram_quantile(0.5, sum by(le) (rate(http_request_duration_ms_bucket{job="$SERVICE-$PROJECT-$STAGE"}[1m])))
  request_duration_p90: histogram_quantile(0.9, sum by(le) (rate(http_request_duration_ms_bucket{job="$SERVICE-$PROJECT-$STAGE"}[1m])))
  request_duration_p95: histogram_quantile(0.95, sum by(le) (rate(http_request_duration_ms_bucket{job="$SERVICE-$PROJECT-$STAGE"}[1m])))
