---
spec_version: '1.0'
indicators:
  response_duration_p50: histogram_quantile(0.5, sum by(le) (rate(http_response_time_milliseconds_bucket{job="$SERVICE-$PROJECT-$STAGE-primary"}[$DURATION_SECONDS])))
  response_duration_p90: histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{job="$SERVICE-$PROJECT-$STAGE-primary"}[$DURATION_SECONDS])))
  response_duration_p95: histogram_quantile(0.95, sum by(le) (rate(http_response_time_milliseconds_bucket{job="$SERVICE-$PROJECT-$STAGE-primary"}[$DURATION_SECONDS])))